apiKey: a917043b7ea630esfsdfdsf311d169a95d12c9f230.28IZrQLuRi8peQqV   #从https://open.bigmodel.cn/login?redirect=%2Foverview注册并获取
xh: ""         #我还没做，填了也没有用
wx: ""        #我还没做，填了也没用
model: characterglm    #chatGLM模式，可选填：characterglm(超拟人大模型),chatglm_pro(pro版),chatglm_std(标准版),chatglm_lite(轻量版)
rwkvPort: 8000    # rwkv端口配置，需要在本地部署rwkv模型，需要6G及以上显存。部署教程详见https://www.bilibili.com/video/BV1hM4y1v76R/?vd_source=b41b8c06d400241b8d0badbe1f821ec9
bot_info:                 #ai角色设定
  user_info: "用户设定"
  bot_info: "ai设定"
  bot_name: "ai名字"
  user_name: "用户名字"
